### ISSUE TITLE
Tags in recipes

### ISSUE THREAD

**Issue by DinnerBeef** [Rearth/Oritech#191]
### Issue description

I noticed many recipes are not using tags for inputs. Looks like its mainly ingots. It would be nice as it makes it easier for pack devs unifying stuff.

### Minecraft version

1.21.1 (Latest)

### Platform

Neoforge

### Loader version

21.1.83

### Fabric API version

NONE

### Oritech version

0.12.2

**Comment by Rearth** [comment]
In which recipes are you missing tags? Most recipes should use tags where applicable for the common ingots (e.g. https://github.com/Rearth/Oritech/blob/1.21/fabricdatagen/src/main/java/rearth/oritech/fabricgen/datagen/RecipeGenerator.java).

**Comment by Rearth** [comment]
Ah I just spotted a few. I'll try and get some fixes done later

**Comment by Rearth** [comment]
Okay so I found one usage of steel items instead of tags. Electrum also didn't use tags before but does now. Am I missing any more tags? I didn't find any missing usages. Changes here:
12c03dc254c65f5cdf8b3ba4ebfa73338d50b833

**Comment by DinnerBeef** [comment]
From a brief look, here is what i found that still needs to be changed. It seems like a lot of a minecraft items that should just be tags. And some other things, like your dusts.
`minecraft:copper_ingot` -> `c:ingots/copper`
`minecraft:gold_ingot` -> `c:ingots/gold`
`minecraft:iron_ingot` -> `c:ingots/iron`
`minecraft:coal` -> `c:coal`
`minecraft:quartz` -> `c:gems/quartz`
`minecraft:copper_ores` (Change Tag) -> `c:ores/copper`
`minecraft:gold_ores` (Change Tag)  -> `c:ores/gold`
`minecraft:iron_ores` (Change Tag) -> `c:ores/iron`
`minecraft:redstone` -> `c:dusts/redstone`
`oritech:copper_dust` -> `c:dusts/copper`
`oritech:gold_dust` -> `c:dusts/gold`
`oritech:iron_dust` -> `c:dusts/iron`

**Comment by Rearth** [comment]
Do we need tags for the vanilla items? Is that really an issue? I'm not aware of any mod that adds another iron ingot that I'd want to support in oritech recipes

**Comment by DinnerBeef** [comment]
Ingots. Yea, not the biggest deal in the world. It's just more the ores and dusts that would be nice to be changed.

**Comment by Rearth** [comment]
Yeah the dusts I missed. I'll add them in the next update, thanks for checking them all. Depending on how motivated I am I might also fix the vanilla ingots

**Comment by ffuentesm** [comment]
I also noticed some items with outdated Tags. 
Mainly Raw Platinum, Raw Nickel using the c: raw_ores/ instead of c: raw_materials/
![image](https://github.com/user-attachments/assets/7571ff2e-1698-4ebb-9604-1c9a068a9b96) ![image](https://github.com/user-attachments/assets/0fa94c23-1536-4e4e-942d-c40c7718f35f)

You are also missing the Block Tags for the storage blocks. You only have their item tag version:
![image](https://github.com/user-attachments/assets/5ba58abf-cefe-4118-8018-2793c6ea8bd7)
![image](https://github.com/user-attachments/assets/5d41d857-4e76-410d-bd87-a3d664c03ef9)
![image](https://github.com/user-attachments/assets/8d5738d9-069c-4651-adeb-78cf7de03f42)

Also, could you add c:plates/plastic to the plastic sheet item, and update the corresponding recipes? 
That would fall in line with other tech mods.
![image](https://github.com/user-attachments/assets/80728c63-d855-4994-9bbf-27c123fb8a5f)


Same for the Exo armor parts not having the c:armors tag, and the vanilla armor tags: minecraft:head_armor, minecraft:chest_armor, minecraft:leg_armor, minecraft:foot_armor
