### ISSUE TITLE
[1.21.1] Incompatibilities with Fuel generator output with other energy mods (nvm i'm just blind)

### ISSUE THREAD

**Issue by SkyRunner55** [Rearth/Oritech#195]
### Issue description

When trying to extract the energy from a fuel generator with another mod energy storage, this dosn't work
Basic generator, bio generator, Lava generator, solar panel works with other energy container mod (i don't know about steam engine)

![2024-12-08_01 11 51](https://github.com/user-attachments/assets/d999f44a-bc00-4b36-b35b-f2c1fe7ac2cc)

![2024-12-08_01 11 58](https://github.com/user-attachments/assets/1ec7515b-ed86-4a38-aee8-d6dd5e75c2c5)

![2024-12-08_01 18 12](https://github.com/user-attachments/assets/271bb3ff-0b44-447d-ab84-09e242e59270)

### Steps to reproduce

1. Generator some energy with fuel generator,
2. Try to import it into something from another mod like [`immersive engineering`](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering) or [Flux network fwork neoforge](https://modrinth.com/mod/flux-network-fork-neoforge/versions)
3. Notice that nothing append

### Minecraft version

1.21.1 (Latest)

### Platform

Neoforge

### Loader version

21.1.83

### Fabric API version

forgified-fabric-api-0.104.0+2.0.19+1.21.1

### Oritech version

0.12.3

**Comment by Volpamonhub** [comment]
The accumulators from Immersive Engineering need their face set to input to accept energy. I don't see an input mode on your screenshot.

I can't test Flux Networks since it's not present in the modpack I'm playing, but I don't have any issues extracting energy from the Fuel Generator using the energy pipes from the Oritech mod. I think you should check the configuration of your setup—it's likely an input/output issue, similar to the capacitors from Immersive Engineering.
![2024-12-08_13 31 24](https://github.com/user-attachments/assets/7ab24fee-295c-4765-b7a2-1ba199d6e144)

**Comment by SkyRunner55** [comment]
![2024-12-08_13 53 18](https://github.com/user-attachments/assets/1061aa6c-6fbd-47f1-a0db-ba9bd2b9f50a)
i didn't notice that the output was THERE , its so hard to see for me
