### ISSUE TITLE
Can live in and breathe oil

### ISSUE THREAD

**Issue by BBoldt** [Rearth/Oritech#27]
Mined into an oil well and fell right in, all is well.

![me inside oil](https://i.imgur.com/xuVGAJK.jpeg)

![just kinda chillin in here](https://i.imgur.com/xB7G0sO.jpeg)

Oritech 0.6.0

**Comment by Rearth** [comment]
Good catch. Adding some sort of status debuffs while in oil might be a good idea. I'll probably include this in a future version

**Comment by BBoldt** [comment]
I've been playing with it on a server, and players are just falling into the oil holes left and right and dying from the fall. At the very least it should behave like water and not air.

**Comment by BLOKBUSTR** [comment]
I noticed that the oil doesn't seem to register any kind of collision/interaction with the player and possibly all other entities too.

I think the oil should apply great friction on the player like lava does, and maybe it can also hinder visibility. However, Fabric API's methods for registering fluids have felt rather weird and insufficient to me the last time I played with them, which was almost a couple years ago, so I don't know how easily this could be implemented or if the methods have improved since.

**Comment by BBoldt** [comment]
I made a short video demonstrating the issue:
[![watch](https://img.youtube.com/vi/58DzQOxWM20/default.jpg)](https://youtu.be/58DzQOxWM20)

**Comment by Rearth** [comment]
Hi, small update on this: I have fixed/implemented this on the main branch now, and it'll be included in the next release. I'm still working on a few other things that I want to finish before the next update, so it'll probably still be a bit before the fix is included. I'll keep this thread open until the release is done

**Comment by Rearth** [comment]
This has been fixed in the latest release (0.7.0), so I'll close this issue for now
