### ISSUE TITLE
[Suggestion] Add metals blocks and nuggets.

### ISSUE THREAD

**Issue by Wizardon777** [Rearth/Oritech#34]
Missing the blocks variants of the ingots added by Oritech, it would be better for mass storage.

The nuggets part is just my request, it'd be nice for symmetry sake 😄

**Comment by Rearth** [comment]
Hm, that would require a whole additional set of textures, and these items/blocks wont have a direct use in the mod. I'll add it to my todo list, but this will be rather low priority, so don't expect an update on this too soon

**Comment by jshipley** [comment]
I'd really like to see this too. While raw ore blocks and metal blocks rarely have a use, not having them makes them take up 9x the storage space.

**Comment by Nova-Katt** [comment]
I second this. Block of Nickel and Block of Platinum would be great for storage, just like with iron, gold, netherite, copper, emerald and diamond. Plus, if the texture is nice it will work nice as a decoration block too! :)
Not all blocks has to have a technical function after all. :3 just like the industrial bar/beam is a decorative "pillar" sort of thing. :D
But mostly, great idea for storage, as you might get a ton of nickel, and chests do get cramped. :)

**Comment by Nova-Katt** [comment]
I'd offer to do those two blocks myself as an optional datapack, but while I've learned the simple datapack stuff such as changing recipes.... i have yet to learn how to actually add blocks yet. :3

Edit/Update: Okay I'm actually going to sit down and start learning this. That way this request could be done WHILE taking the workload away from you.
And who knows, if I make a good enough job you could always include it into a future update later.
My plan is to learn how to add items, and blocks, via datapack, and then I'll fix compressed blocks for all the ingots (nickel, platinum, electon, duratium, etcetera), and I will also fix for the raw ores, just like we have block of raw copper and block of raw iron, and so on.
So yeah, it will be a bit of work as it's more than just nickel and platinum, but I'll see what I can do.
Step 1: learn how to do this thing!
I'll keep you updated. :P

**Comment by jshipley** [comment]
The art work is really the hardest part of this. The code part is just adding a few lines to the block registration code and block/recipe datagen.

If you create the art assets, I could write the code and submit a PR to add the blocks.

I wouldn't say no to blocks for all the metals (and for nickel/platinum raw ores), but I have noticed in my gameplay that I'm more likely to have chests full of nickel and platinum, while I mostly make the alloys when I need them and have at most a few extra stacks of ingots.

**Comment by Nova-Katt** [comment]
Oh, absolutely. I was already fumbling around trying to learn how to add blocks in data packs (Turns out it's a bit of a headache compared to mods, which I also don't know).
I will still try to learn it one day, but I can absolutely focus on the art first of all. :)
**The plan involves blocks for:**
**Ingots:** adamant, biosteel, duratium, electrum, energite, nickel, platinum, prometheum and steel.
**Raw:** nickel, platinum and perhaps silicon
**Others:** Haven't decided yet, but if I get a feel for it, I might make blocks for some of the other materials as well, like biopolymer, plastic, and stuff like that.. but we'll see. :) the metals are prio.
Will be an interesting challenge as well with some of those blocks, most specifically promethium. :)

**Comment by Nova-Katt** [comment]
Here is a little peek at what I have currently so far.
Steel, Nickel, Platinum, Electrum, Energite, Biosteel, Adamant, and then Raw nickel and Raw platinum.
I'm not entirely happy with the pink fuzzy Energite, so we'll see what I do with that (unless you like it as it is).
The one by Duratium is just a placeholder, so it's not going to look like that. :)
Let me know if you like them, or if you don't like them and need some changes. I'm having fun playing around.
![oritech preview blocks](https://github.com/user-attachments/assets/078032c0-a076-4cbb-8d47-f0c11756d89f)
Also if you have any ideas for additional blocks other that raw silicone, biomass, duratium and promethium, let me know! :)

**Comment by jshipley** [comment]
I'm mostly liking it, here are some ideas:

The energite might look better if it gets some of the almost white highlight in it. Another thing that might help is if the highlights were more diagonal like all of the other metal blocks. It kind of looks like there's a big bubble in the block.

The duratium also might look good with a texture similar to the adamant, but with the darker colors.

Biopolymer could look kind of like a block of dried kelp.

A stack of plastic sheets (sort of like what Industrial Foregoing uses?) might also look good.

The quartz dust and silicon powder blocks could look like sand/powdered concrete with an appropriate color.

**Comment by BLOKBUSTR** [comment]
I'd like to add that the Promethium ingot *might* be subject to change, especially since its current texture is inconsistent with most of the other ingots. The rest of the ingot shapes may also be adjusted and cleaned up, but I intend to preserve their colors, so you won't have to significantly revise the colors or style of your own blocks.

So far, the Steel and Biosteel blocks seem really fitting. I think most of the other blocks could benefit from slightly smaller color palettes and a little more contrast, like what you did with the Raw Platinum, which I also really like.

The Raw Nickel block could be revised a bit, giving it a more clear pattern to better represent raw nickel. I'm actually trying to revise the item texture to make it more consistent with the vanilla raw ores, but I haven't achieved a satisfactory result yet. I think referencing the vanilla raw ore blocks could help with your own block texture too. I'm hoping to submit a new PR of the revised item textures soon.

As for additional block ideas, I think a Fluxite block could be cool, having a diamond-shaped pattern like the pre-1.13 emerald block, or perhaps even the Olivine block from Better Than Adventure.

**Comment by Nova-Katt** [comment]
Ooooh those are some great compliments, and feedback, and ideas. Thank you! And yeah I was unsure of the bubble thing on energite, so it was a bit of a gamble, but I will revise it for sure. :)
Great idea with the duratium too, and well all the ideas you two posted are great. a stack of plastic sheets was really smart, I'll fix that for sure! And the fluxite pre-emerald was a great idea/inspiration.
All in all, great. I have work to do, and I will put the prometeum block on freeze until I know what the future look of the ingot will be. :)

**Comment by Rearth** [comment]
Thse already looking great, thanks for all the work. Prometheum blocks aren't really something I want to add, as they don't fit the their idea of a mystical high-tech ingot with wires and electronics in it too well in my opinion

**Comment by BLOKBUSTR** [comment]
That makes sense, especially since I imagine Prometheum isn't a resource intended to be mass-produced easily, if at all. I did consider the idea of a decorative Prometheum block looking somewhat like a command block with emissive textures and all, but it simply wouldn't be practical for mass storage as one would probably immediately use the ingots to craft the tools and then forget about it.

**Comment by Nova-Katt** [comment]
Hard agree. I just yesterday started to work on the prometheum pickaxe.... and realized how big of an undertaking it is and how much materials and work it takes to get just 1 single ingot... so yeah... a storage block of prometheum felt quite far away all of a sudden. x)

I did think of a lot of other uses for prometheum instead, but that's a topic for another thread. :P

So back to topic, I'll have more time to work on textures on sunday, and have added plastic sheets and fluxite as new items to the worklist, in addition to revisions of the blocks you've mentioned. :)

**Comment by jshipley** [comment]
I agree on prometheum blocks being unnecessary.  I don't think that they'd ever be anything more than a prestige/trophy block sort of like a netherite block.

**Comment by Nova-Katt** [comment]
As per the texture thread on discord, I've done plenty of updates to pretty much all of the textures.

Most of them have multiple variants. That way I could try different styles and tones, and you can basically pick your favorite. :D

Raw Nickel was tricky because painting ore-clump-blocks was not my area of expertise, but I think it's better now and closer to the vanilla raw blocks too.

Plastic Sheets was tricky because they needed sides and top/bottom, and I have no way of seeing them together in photoshop, so I just hope one of the two tops fits with one of the 3 sides.

If I'm allowed to be proud of something, I really do like the fluxite blocks, if I may say so myself. :D

I will attach the overview all-textures image, but I also have them all split into actual 16x16 texture files in the attached .rar file aswell. :)

Let me know what you think of this update. And if you have any addtional feedback or ideas.

_(Oh, and while I usually go by NovaKatt everywhere, it was taken in Minecraft, so... I go by NovaKatt69 there instead :P)_

**Pack of textures here!** [oritech block by NovaKatt69.zip](https://github.com/user-attachments/files/17578177/oritech.block.by.NovaKatt69.zip)
![oritech-textures update](https://github.com/user-attachments/assets/f37eafea-6448-4ad3-9ce8-e48ad303c0cc)
