### ISSUE TITLE
Monorail Tram plz

### ISSUE THREAD

**Issue by AtosAurora** [Rearth/Oritech#44]
### Describe the feature you'd like

English is not my native language; please excuse typing errors.
Vanilla minecarts are too complex in terms of transporting items and fluids, and I think the monorail (as in Satisfactory) suits the style of this mod well. Trains can draw power from the tracks. Automatic loading and unloading of items and fluids at the station (and powering the tracks) is possible. Trains are able to run automatically according to pre-programmed routes.
↓Monorail in the Satisfactory (image from Bing)
![1722425049232](https://github.com/user-attachments/assets/227a3418-df64-49fb-98b3-60855b0a1923)
The mod you made is very beautiful and interesting, I hope my suggestions will make it better!
Thanks for reading my suggestions!

**Comment by jshipley** [comment]
It's too bad that Little Logistics is not available in Fabric, because that would do a lot of what you're asking for. Maybe someday (when Little Logistics is updated to 1.21+) you could use Sinytra Connector to load Oritech in Neoforge and play with Oritech and Little Logistics (or with Create, which also has the kind of trains you're describing).

The energy/fluid storage blocks work with comparators, can be placed with dispensers, and can be broken with pistons. Using this, you can build a fairly simple loader/unloader that places empty tanks, fills them, and then breaks them (or places full tanks, empties them, and then breaks them).

After creating a loader/unloader, then it's just item transport.

Oritech has drone ports, which can be used to transfer items long distance.

You could also use a hopper to put the storage blocks into a chest minecart, and deliver that to another loading/unloading station.

**Comment by Rearth** [comment]
Hi, honestly while the trains are a cool idea, thats out of scope of what I want to do with Oritech. Still, thanks for the idea.
