### ISSUE TITLE
Stabilized Enchanter accepts stick as input and gives error enchantments

### ISSUE THREAD

**Issue by jshipley** [Rearth/Oritech#96]
### Issue description

![image](https://github.com/user-attachments/assets/cef4a11f-c65a-48e9-8138-a76053ec7f58)

The stabilized enchanter should not try to provide possible enchantments for sticks.

I've tried a bunch of other random items, and the enchanter doesn't try to enchant them. The enchanter also doesn't try to enchant books, which could be possible.

### Minecraft version

1.21.1 (Latest)

### Fabric loader version

0.16.5

### Fabric API version

0.104.0+1.21.1

### Oritech version

0.9.1

**Comment by Rearth** [comment]
Huh, is that with other mods? The enchanter just lists what's available in minecraft and listed as applicable. This also doesn't happen for me in a blank environment, so I think the issue here is other mods creating invalid enchantments. Create a list of invalid items or enchantments from other mods just seems like trouble. The book not being enchantable is by design

**Comment by jshipley** [comment]
It could be other mods. I'll try to reproduce in a clean environment, and also try to reproduce with Bumblezone (the only other mod installed that I'm aware of that might be adding enchantments).

**Comment by jshipley** [comment]
It went away when I disabled Dungeons and Taverns.

Since this is just another mod offering bad enchants for an item and not related to Oritech, I'm going to close the issue.
